{
 "title": "Diabetes mg/dl",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Glucose",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "mg/dl",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glucose",
     "select": [
      [
       { "params": [ "value_mgdl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Delta",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Δ mg/dl",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glucose",
     "query": "SELECT derivative(mean(\"value_mgdl\"), 5m) FROM \"glucose\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value_mmol" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glucose",
     "select": [
      [
       { "params": [ "value_mgdl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HbA1c",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glucose",
     "query": "SELECT ((2.59 + mean(\"value_mmol\"))  / 1.59) FROM \"glucose\" WHERE time <= now() group by time($interval)",
     "select": [
      [
       { "params": [ "value_mmol" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1.59" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Glucose",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "measurement": "glucose",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "mtanda-histogram-panel",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "glucose",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glucose",
     "select": [
      [
       { "params": [ "value_mmol" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}